import Head from 'next/head'
import Image from 'next/image'
import imageAPropos from "../public/a-propos.jpg";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>A propos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles['a-propos']}>
        <Image src={imageAPropos} alt='a-propos'/>
        <div className={styles.aPropos}>
          <h3 className={styles.center}>A propos de moi</h3>
          <div className={styles.aProposText}>
            <p>Je suis Firmin, coach sportif diplomé depuis 4 ans.
3 ans d ‘expérience en salle de sport fitness. 
Je suis un coach polyvalent capable de pratiquer tous types de séances tel que la boxe, les cours de  fitness etc.
Je suis formé sur la plus grande plateforme de cours collectifs des mills sur les cours de body combat, rpm, bodybalance, cxworce, pump ...
Tous ces cours m’ont permis d’aquérir un panel d’exercices et de compétences techniques qui me permettent d’obtenir sur ma clientèle le meilleur des résultats. </p>
            <p>Je suis un ancien militaire avec 11 ans de service.
La pratique de ce métier m’a permis acquérir une exigence professionnelle dans l’exercice de mon métier de coach sportif. 

Chaque jour qui se fait, je donne le meilleur de moi-même pour donner à ma clientele un service irréprochable pour le meilleur des résultats .
</p>
          </div>
        </div>
      </section>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
