import Head from 'next/head'
import Image from 'next/image'
import imageAPropos from "../public/a-propos.jpg";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>A propos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles['a-propos']}>
        <div style={{display:'flex'}}>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12822.435602815618!2d0.6144645083454641!3d44.201429273911124!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12abb31aff85830f%3A0x40665174815bbf0!2sAgen!5e0!3m2!1sfr!2sfr!4v1627733716286!5m2!1sfr!2sfr"  height="450" style={{border:0, width:'80%'}} allowfullscreen="" loading="lazy"></iframe>
      <form action="" width='20%'>
        <div style={{display:'flex'}}>
          <label htmlFor="nom">Nom</label>
          <input type="text" name='nom'/>
          <label htmlFor="prenom">Prenom</label>
          <input type="text" name='prenom'/>  
        </div>
        <label htmlFor="message">Message</label>
        <textarea name="message" cols="30" rows="10"/>
        <button>Envoyer</button>
      </form>

        </div>
        <div className={styles.aPropos}>
          <a href="tel:+33771022984">07.71.02.29.84
          <br />
          Agen
          </a>
        </div>
      </section>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
