import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Page LP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.home}>
        <h1 className={styles.text}>Trouve ici une autre vision du coaching</h1>
        <div className={styles.text} style={{textAlign:'center'}}>
          <h1>Quand tu seras sur le point de laisser tomber</h1>
          <h1>Je serai là pour te rappeler pourquoi tu as commencé</h1>
        </div>
      </section>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
