import Head from 'next/head'
import Image from 'next/image'
import image1 from "../public/mes-prestations-1.jpg";
import image2 from "../public/mes-prestations-2.jpg";
import image3 from "../public/mes-prestations-3.jpg";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mes prestations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles['a-propos']}>
        <Image src={image1}  alt='mes-prestations'/>
        <div className={styles.aPropos}>
          <h3 className={styles.center}>Coaching 1 to 1</h3>
          <div className={styles.aProposText}>
            <ul style={{marginLeft:'32px'}}>
              <li>Développement musculaire</li>
              <li>Raffermissement musculaire</li>
              <li>Développement de la coordination</li>
              <li>Perte de poids</li>
              <li>Augmentation des performances physiques</li>
              <li>Séance de boxe</li>
              <li>Séance de training, de stretching</li>
            </ul>
            <p> Envie de changement, de perturber vos habitudes ?<br /> 
Je suis la personne qu’il vous faut pour vous faire prendre conscience que le sport est important pour vous.
<table style={{marginTop: '16px', width:'100%'}}>
<thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tarif :</td>
            <td>30 min</td>
            <td>30€</td>
        </tr>
        <tr>
            <td>{" "}</td>
            <td>1h</td>
            <td>60€</td>
        </tr>
        <tr>
            <td>{" "}</td>
            <td>1h30</td>
            <td>80€</td>
        </tr>
    </tbody>
</table>
            </p>
          </div>
        </div>
      </section>
      <section className={styles['a-propos']}>
        <Image src={image2} alt='mes-prestations'/>
        <div className={styles.aPropos}>
          <h3 className={styles.center}>Coaching pour les entreprises</h3>
          <div className={styles.aProposText}>
            <ul style={{marginLeft:'32px'}}>
              <li>Développement musculaire</li>
              <li>Raffermissement musculaire</li>
              <li>Développement de la coordination</li>
              <li>Perte de poids</li>
              <li>Augmentation des performances physiques</li>
              <li>Cours de boxe</li>
              <li>Cours de training, de stretching</li>
            </ul>
            <p> JE ME REND DANS VOTRE ENTREPRISE POUR VOTRE REMISE EN FORME <br /> 

Des séances accessibles à tous pour vous dépenser et vous sentir au top pour une journée de travail. 
<table style={{marginTop: '16px', width:'100%'}}>
<thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tarif :</td>
            <td>1h</td>
            <td>50€</td>
        </tr>
        <tr>
            <td>{" "}</td>
            <td>1h30</td>
            <td>70€</td>
        </tr>
    </tbody>
</table>
            </p>
          </div>
          <p style={{textAlign:'center'}}>
          8 séances  achetées 2 Séances OFFERTES <br />
          16  séances  achetées 4 Séances OFFERTES <br />
          24  séances  achetées 6  Séances OFFERTES

          
          </p>
        </div>
      </section>
      <section className={styles['a-propos']}>
        <Image src={image3} alt='mes-prestations'/>
        <div className={styles.aPropos}>
          <h3 className={styles.center}>Coaching de groupe</h3>
          <div className={styles.aProposText}>
            <ul style={{marginLeft:'32px'}}>
              <li>Développement musculaire</li>
              <li>Raffermissement musculaire</li>
              <li>Développement de la coordination</li>
              <li>Perte de poids</li>
              <li>Augmentation des performances physiques</li>
              <li>Cours de boxe</li>
              <li>Cours de training, de stretching</li>
            </ul>
            <p> TROUVE ICI UNE AUTRE VISION DU COACHING COLLECTIF- <br />
            Chaque séance sera adaptée à vos capacités et à votre environnement.
Un coaching ciblé qui correspond à vos attentes selon des objectifs prédéfinis lors de notre premier rendez-vous.
<table style={{marginTop: '16px', width:'100%'}}>
<thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tarif :</td>
            <td>1h</td>
            <td>50€</td>
        </tr>
        <tr>
            <td>{" "}</td>
            <td>1h30</td>
            <td>70€</td>
        </tr>
    </tbody>
</table>
            </p>
          </div>
          <p style={{textAlign:'center'}}>
          8 séances  achetées 2 Séances OFFERTES <br />
          16  séances  achetées 4 Séances OFFERTES <br />
          24  séances  achetées 6  Séances OFFERTES

          
          </p>
        </div>
      </section>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
